export { default as Header } from './Header';
export { default as RootModal } from './RootModal';
export { default as Authentication } from './Authentication';
export { default as Main } from './Main';
export { default as Shop } from './Shop';
export { default as Events } from './Events';
export { default as TechService } from './TechService';
// export { default as PaymentListener } from './PaymentListener';
export { default as Profile } from './Profile';
export { default as NotFound } from './NotFound';
export { default as Loading } from './Loading';
export { default as Cart } from './Cart';
// export { default as Clients } from './Clients';
export { default as Programs } from './Programs';
// export { default as Schedules } from './Schedules';
// export { default as Specialists } from './Specialists';
// export { default as Notifications } from './Notifications';
// export { default as ProgramPayment } from './ProgramPayment';
export { default as Statistics } from './Statistics';
export { default as AdminPanel } from './AdminPanel';

export * from './Support';
